#install build and deploy

language: node_js
node_js : 
  - "stable"
install: npm install
script: npm test
deploy:
  app: test-egads-website
  provider: heroku
  api_key: 
    secure: wXUT7yYXYmpjQ0uVadNaUhmu9Ax4Szf6XfdSvnob+1QoQ2t4FknuRfWmHIp0vym+8dmcf0RJhss56pZFTP+sSjjpsxTDWVu3p2h6rSI3TSkYnDYUxzuoMp36bIwmF3lcRXSPzg0n4+QO0pzuQuliSHjKjpQcsD8JrsPB/uzMYPg9g0aeJLvLuDvvozyZoy9h2Vxdz6uqkB4kRaODisyTJXz4tRXR7cFZRH/XtX5jIvuMuTWkvFwng1fNanVXU5cumHA12Qrxb/NoLnOm3pgEReidAzDdGspI2rb67TMKgTuN+oRnzCW/255Bb//GL6GCxKetThtlH85WxGUaYf8XNA+u0GsU/sGCkJZlBabXy+7dY543R1aj198d6JwOmK5FkKUlrsuJ5vz6WP0LWKLnHjRb0K8xn1Fiy8gUn3zfFyVKYPZNihyHakyRDiE24NQZwLdRZ/KrZ5iMsdn3ic2P9+FWURmsOWqwY54rFnvcyEat0XZGnSB5XVijr5xdlVXf8GcMZDmgJN9tSqDVqdl6Isidhqonv/F7P4Mj3Q9K3+1Ag42wbQn34E37lplngNyQt5nEP5d11zP73niDLPFiJ+ig529UwpZgjnu9SFi27X5nFwFyb7tQN0jaDz2/VTp+Bhl+5m96cejCRbtNsDJrcRKl1bDDxDWTPuaFy5NI4PE=
branches:
  only:
    - master